#%RAML 1.0 NamedExample
getUserById: {
                "id": "d0ff4b09-b179-4a54-a3b1-dc6090aface2",
                "email": "administrador@hotmail.com",
                "nome": "Administrador Teste",
                "perfil": "A",
                "situacao": "A",
                "endereco": {
                  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                  "cep": "04210061",
                  "logradouro": "Rua Oliveira Alves",
                  "complemento": "Apto. 41",
                  "numero": "608",
                  "bairro": "Ipiranga",
                  "localidade": "São Paulo",
                  "uf": "SP"
                }
              }